"""Fix naming

Revision ID: f210aef05d21
Revises: 6e078b28dff7
Create Date: 2025-10-20 21:58:15.991911

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "f210aef05d21"
down_revision: Union[str, Sequence[str], None] = "6e078b28dff7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["parent_id"], ["activity.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_activity_name"), "activity", ["name"], unique=False)
    op.create_table(
        "building",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("address", sa.String(length=255), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_building_address"), "building", ["address"], unique=False)
    op.create_table(
        "organization",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("phones", sa.JSON(), nullable=False),
        sa.Column("building_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["building_id"], ["building.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_organization_name"), "organization", ["name"], unique=False)
    op.drop_constraint(op.f("organization_activity_ibfk_1"), "organization_activity", type_="foreignkey")
    op.drop_constraint(op.f("organization_activity_ibfk_2"), "organization_activity", type_="foreignkey")
    op.drop_index(op.f("ix_organizations_name"), table_name="organizations")
    op.drop_table("organizations")
    op.drop_index(op.f("ix_buildings_address"), table_name="buildings")
    op.drop_table("buildings")
    op.drop_index(op.f("ix_activities_name"), table_name="activities")
    op.drop_table("activities")

    op.create_foreign_key(
        None, "organization_activity", "organization", ["organization_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(None, "organization_activity", "activity", ["activity_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "organization_activity", type_="foreignkey")
    op.drop_constraint(None, "organization_activity", type_="foreignkey")
    op.create_foreign_key(
        op.f("organization_activity_ibfk_2"),
        "organization_activity",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("organization_activity_ibfk_1"),
        "organization_activity",
        "activities",
        ["activity_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_table(
        "organizations",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("phones", mysql.JSON(), nullable=False),
        sa.Column("building_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["building_id"], ["buildings.id"], name=op.f("organizations_ibfk_1"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(op.f("ix_organizations_name"), "organizations", ["name"], unique=False)
    op.create_table(
        "activities",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", mysql.VARCHAR(length=128), nullable=False),
        sa.Column("parent_id", mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["parent_id"], ["activities.id"], name=op.f("activities_ibfk_1"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(op.f("ix_activities_name"), "activities", ["name"], unique=False)
    op.create_table(
        "buildings",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("address", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("latitude", mysql.FLOAT(), nullable=False),
        sa.Column("longitude", mysql.FLOAT(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(op.f("ix_buildings_address"), "buildings", ["address"], unique=False)
    op.drop_index(op.f("ix_organization_name"), table_name="organization")
    op.drop_table("organization")
    op.drop_index(op.f("ix_building_address"), table_name="building")
    op.drop_table("building")
    op.drop_index(op.f("ix_activity_name"), table_name="activity")
    op.drop_table("activity")
    # ### end Alembic commands ###
